# Generated by Django 3.1.7 on 2021-03-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='facebook_link',
            field=models.TextField(blank=True, null=True, verbose_name='Lien vers votre page facebook'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='instagram_link',
            field=models.TextField(blank=True, null=True, verbose_name='Lien vers votre page instagram'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='linkedin_link',
            field=models.TextField(blank=True, null=True, verbose_name='Lien vers votre page linkedin'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='twitter_link',
            field=models.TextField(blank=True, null=True, verbose_name='Lien vers votre page twitter'),
        ),
    ]
