# Generated by Django 3.1.7 on 2021-03-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210316_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
